### Sign up
POST http://localhost:8030/api/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "12345678"
}

### Sign in
POST http://127.0.0.1:8030/api/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}

### me
POST http://127.0.0.1:8030/api/me HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 20|qKOvlgYjrYeidgWWRYDK2r5fYZHWcqNoZjlZ5h4Y

### logout
POST http://127.0.0.1:8030/api/logout HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 11|7xZFeggHD6SjBNzUCIjvNMo16jEp3ZCNYqpItFHC

### updateProfileDetails
POST http://127.0.0.1:8030/api/updateProfileDetails HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 23|aJEbD09M7wrXrWzSp44DjFfqQDzsMV4IcYL1i4G2

{
    "email": "test2@test.com",
    "name": "test3"
}

### Get Barcode product
GET http://127.0.0.1:8030/api/get_barcode_products/5449000000996 HTTP/1.1
Accept: application/json
Content-Type: application/json

### Get all barcode product
GET http://127.0.0.1:8030/api/get_all_food  HTTP/1.1
Accept: application/json
Content-Type: application/json

### Save meal
POST http://127.0.0.1:8030/api/save_meal HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 18|18qfJYPDpDUrVc3RleLoQyukpQhTijqPx3dPlKRi

{
    "meal": "lunch",
    "intake_serving_size": "500",
    "food_id": "3"
}

### get current meals
GET http://127.0.0.1:8030/api/get_current_meals HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 26|hysv3CTWqSrkdEnK20vNyOjOqhhxohfxb04jjmcU



### get daily summary
GET http://127.0.0.1:8030/api/get_daily_summary HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

### get current meals
GET http://127.0.0.1:8030/api/get_current_meals HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 26|hysv3CTWqSrkdEnK20vNyOjOqhhxohfxb04jjmcU


### get weekly summary
GET http://127.0.0.1:8030/api/get_weekly_summary HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

### get weekly summary
POST http://127.0.0.1:8030/api/get_diabetes/70.2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

###
GET http://127.0.0.1:8030/api/get_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

### Create Recipe
POST http://127.0.0.1:8030/api/create_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "recipe_name": "Pineapple Tarts",
    "recipe_ingredients": "flour, corn starch, salt, icing sugar, unsalted butter, egg yolks, condensed milk, pineapple jam, sugar",
    "recipe_instructions": "If you are using canned pineapple slices, drain the pineapple slices and then squeeze the extra water/juice with your hands. Blend the canned pineapples until they are mushy, about 10 seconds. If you use fresh pineapples, remove the skin, cut into pieces and blend for 10 seconds.",
    "recipe_source": "https://rasamalaysia.com/recipe-pineapple-tarts/",

}

### Get by recipe by id
GET http://127.0.0.1:8030/api/get_recipe_by_id/2 HTTP/1.1
Accept: application/json
Content-Type: application/json

### create user recipe
POST http://127.0.0.1:8030/api/create_user_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 15|ipa0l7wUNhoEt1pSzdVCUcK2D7meCsqjvw2iEpnq

{
    "ur_breakfast": "1",
    "ur_lunch": "2",
    "ur_snacks": "3",
    "ur_dinner": "4"

}

### Get by user id UR
GET http://127.0.0.1:8030/api/get_by_userID HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 15|ipa0l7wUNhoEt1pSzdVCUcK2D7meCsqjvw2iEpnq

### update ur
POST http://127.0.0.1:8030/api/updateUr/ur_lunch HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 15|ipa0l7wUNhoEt1pSzdVCUcK2D7meCsqjvw2iEpnq

### count recipe
GET http://127.0.0.1:8030/api/count_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8030/api/get_lunch_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

