### Sign up
POST http://localhost:8030/api/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "test",
    "email": "test@test.com",
    "password": "12345678"
}

### Sign in
POST http://127.0.0.1:8030/api/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "12345678"
}
### me
POST http://127.0.0.1:8000/api/me HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

### Get Barcode product
GET http://127.0.0.1:8030/api/get_barcode_products/5449000000996 HTTP/1.1
Accept: application/json
Content-Type: application/json

### Get all barcode product
GET http://127.0.0.1:8000/api/get_all  HTTP/1.1
Accept: application/json
Content-Type: application/json

### Save meal
POST http://127.0.0.1:8030/api/save_meal HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 26|hysv3CTWqSrkdEnK20vNyOjOqhhxohfxb04jjmcU

{
    "meal": "breakfast",
    "intake_serving_size": "500",
    "food_id": "3"
}

### get current meals
GET http://127.0.0.1:8030/api/get_current_meals HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 26|hysv3CTWqSrkdEnK20vNyOjOqhhxohfxb04jjmcU



### get daily summary
GET http://127.0.0.1:8030/api/get_daily_summary HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

### get current meals
GET http://127.0.0.1:8030/api/get_current_meals HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 26|hysv3CTWqSrkdEnK20vNyOjOqhhxohfxb04jjmcU


### get weekly summary
GET http://127.0.0.1:8030/api/get_weekly_summary HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

### get weekly summary
POST http://127.0.0.1:8030/api/get_diabetes/70.2 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 21|UU0nm8BZcAxxHGdyzLG0cCh8YsLglR9AB993XWob

###
GET http://127.0.0.1:8030/api/get_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

### Create Recipe
POST http://127.0.0.1:8030/api/create_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "recipe_name": "Pineapple Tarts",
    "recipe_ingredients": "flour, corn starch, salt, icing sugar, unsalted butter, egg yolks, condensed milk, pineapple jam, sugar",
    "recipe_instructions": "If you are using canned pineapple slices, drain the pineapple slices and then squeeze the extra water/juice with your hands. Blend the canned pineapples until they are mushy, about 10 seconds. If you use fresh pineapples, remove the skin, cut into pieces and blend for 10 seconds.",
    "recipe_source": "https://rasamalaysia.com/recipe-pineapple-tarts/",

}

### create user recipe
POST http://127.0.0.1:8030/api/create_user_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|M0o51lPkpM5RHrGNF7wtmKx7Oa48N0SKS0vldqYB

{
    "ur_breakfast": "1",
    "ur_lunch": "2",
    "ur_snacks": "3",
    "ur_dinner": "4"

}

###
GET http://127.0.0.1:8030/api/count_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json

###
GET http://127.0.0.1:8030/api/get_lunch_recipe HTTP/1.1
Accept: application/json
Content-Type: application/json